language: node_js
node_js:
  - 9
cache: 
  directories: 
    - node_modules
script:
  - npm run test:unit
deploy:
  provider: npm
  email: "topephysics@gmail.com"
  api_key: "c01a93df-4c6d-4175-8958-44c5e9c82106"